spring:
  datasource:
    url: jdbc:mysql://${CONNECT_ADDRESS}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_TYPE}
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${RED_URI}